### ISSUE TITLE
Off lattice relax example cannot  run. 

### ISSUE THREAD

**Issue by mikaholic** [spparks/spparks#35]
The examples/relax does not run properly with release bc8e328. Error pops out that 

SPPARKS (16 Jan 2023) 
Created box = (0 0 -0.5) to (32 32 0.5)
    1 nu 1 nu 1 processor grid
Creating sites ...
    1024 sites
Segmentation fault

**Comment by scottwsides** [comment]
I have verified the same error (for a docker container running centos7) that 16Jan23 and 19Sep22 give seg fault for relax example

**Comment by scottwsides** [comment]
Here's a gdb backtrace:  (BTW, the 4 versions of the code available at this github site all give the same error)
-------------------------------------------------------

SPPARKS (24 June 2021)
Created box = (0 0 -0.5) to (32 32 0.5)
  1 by 1 by 1 processor grid
Creating sites ...
  1024 sites

Program received signal SIGSEGV, Segmentation fault.
0x000000000041419a in SPPARKS_NS::CreateSites::structured_lattice() ()
Missing separate debuginfos, use: debuginfo-install glibc-2.17-326.el7_9.x86_64 libgcc-4.8.5-44.el7.x86_64 libjpeg-turbo-1.2.90-8.el7.x86_64 libpng-1.5.13-8.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 zlib-1.2.7-21.el7_9.x86_64
(gdb) backtrace
#0  0x000000000041419a in SPPARKS_NS::CreateSites::structured_lattice() ()
#1  0x0000000000417901 in SPPARKS_NS::CreateSites::command(int, char**) ()
#2  0x000000000042f917 in SPPARKS_NS::Input::execute_command() ()
#3  0x000000000042fd08 in SPPARKS_NS::Input::file() ()
#4  0x0000000000422acc in main ()

**Comment by scottwsides** [comment]
So Steve Plimpton's off-lattice-bug branch has been working for me. Looking forward to those fixes being pushed to main. Here's another error 

<img width="559" alt="Screen Shot 2023-03-23 at 5 07 26 PM" src="https://user-images.githubusercontent.com/13578795/227384213-ce9c63d7-4db6-4975-be93-cc50e737c9e7.png">

However, if I comment out the DEBUG check in the file mentioned above ... 3D sims seem to work. 2D sims are good for all the parameters I've checked. Is commenting out this check ok?

**Comment by jamitch-snl** [comment]
With the 6Sep23 this issue should be fixed -- off-lattice bug.
