### ISSUE TITLE
Where is CuO3.spins.gz?

### ISSUE THREAD

**Issue by bardiche89** [spparks/spparks#37]
Hello,

I downloaded the current release of SPPARKS and wanted to try the sintering example, however I cannot find the CuO3.spins.gz file  which is mentioned in the README file located in /examples/sintering/

Am I looking in the right place?

Many Thanks

B

**Comment by jamitch-snl** [comment]
Hello B,

The file is 38Mb -- which exceeds file size allowed by github.

Send me an email -- and I will reply with the file.

jamitch at sandia dot gov

J

**Comment by jamitch-snl** [comment]
The examples/sintering input script used a 40 MB file of site values, which is too large to include in the repo.
Posted this file on Google Drive, and the README now explains how to grab it.
