### ISSUE TITLE
Commit to master broke build?

### ISSUE THREAD

**Issue by scottwsides** [spparks/spparks#46]
This error just started occurring, close to latest commit to master. Does this error ring a bell?

<img width="1179" alt="Screen Shot 2023-09-06 at 11 26 05 AM" src="https://github.com/spparks/spparks/assets/13578795/0f0c3f12-fc5f-4096-82ba-073d2274f345">

**Comment by jamitch-snl** [comment]
Thanks Scott.  I'll look into that.  Its defintely related to recent commit but not sure where to point the blame.  I'll look at it and respond back here after that.

**Comment by jamitch-snl** [comment]
@scottwsides see message

**Comment by scottwsides** [comment]
The following builds... so the error isnt too far back ;-)

```
RUN cd /home/hpcuser \
    && git clone --depth=2 https://github.com/spparks/spparks.git spparks-$SPPARKS_VERSION \
    && cd spparks-$SPPARKS_VERSION \
    && git checkout 4abb48c25777bd013e86232902112c71a0220b5d
```

**Comment by jamitch-snl** [comment]
@scottwsides 
Error you have relates to 'serial' build.  I don't have any problems with build but we rarely do builds for serial runs.  Somehow that aspect of build is broken.  I just did a merge yesterday which in all liklihood broke the build for serial.  But I'm still looking at this.  Also I note that you are not building with stitch.

**Comment by scottwsides** [comment]
Understood on serial. Never heard of stitch

**Comment by jamitch-snl** [comment]
@scottwsides 
Your error is not directly related to mpi although I have evidence of actual mpi errors when trying to build in serial.
What version of g++ are you using?

**Comment by scottwsides** [comment]
I stage my docker builds so its kinda hard to get at compiler used ... but here's the development env in my build stage for docker

# ----------------------------------------------------------------
# Needed for configuring image generation and building source
# ----------------------------------------------------------------
RUN cd / \
    && yum -y groupinstall development \
    && yum install -y zlib-devel libjpeg-turbo-devel libpng-devel \
    && yum clean all \
    && rm -rf /var/cache/yum

**Comment by jamitch-snl** [comment]
@scottwsides 
I have built both parallel and serial executables and no errors.  build error you show is likely related to your compiler.   Its probably a bit old for the form of initializer.  I don't think your compiler needs to be the absolute latest but it can't be too old.  Too old is probably something like gcc 4.8.5 or maybe 5.4.0.  I'm not exactly sure what the compiler requirement is.  I have been doing development mostly with gcc 10.1.  I have also been using intel 19.  The only way to tell is to somehow load a different compiler in your tool chain.  CENTOS 7 (which is what it looks like you are using) is probably pretty dated if its based off of RHEL 7.    Sorry that this may not be the answer you wanted to hear.

**Comment by scottwsides** [comment]
Understood, I'll take a look. Dependence on intel compiler is rough ;-)

**Comment by scottwsides** [comment]
So I was using old g++ compiler (4.8.5). mpi build uses mpicxx wrapper... so I'm not sure what flags and/or magic is getting set there so that it didnt fail. Anyway... I have images where I upgraded to g++ 8.x.x and that seems to work. There's some weird yum install gymnastics that needs to be performed, but I had that figured out for the other images. More specifically that lets me set  flags=c++17 (instead of c++11) and presto.  This is good... it will force me to upgrade all my images to use same compiler ;-) 

Cheers,

**Comment by scottwsides** [comment]
Actually c++11 is fine it seems. Upgrading compiler was main thing.

**Comment by jamitch-snl** [comment]
Great.  I'm going to close this issue.  Thanks.
